
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjdtynqvlswpxwjpqylw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZHR5bnF2bHN3cHh3anBxeWx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTMzOTAsImV4cCI6MjA2MTg2OTM5MH0.6nW7ENJUHSzM7lF_A0MIvFt5xKmAMxXnquEAuIj5IB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
